framework:
    secret: '%env(APP_SECRET)%'

    # Configuration de la session
    session:
        handler_id: null
        cookie_secure: true
        cookie_samesite: 'lax'
        storage_factory_id: session.storage.factory.native

    # Activation de la protection CSRF
    csrf_protection:
        enabled: true

    # Configuration pour forcer HTTPS
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port']

    # Configuration pour les assets
    assets:
        base_urls: ['https://back-partiel.malakayalauvergnat.com/']

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file