nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: []
        allow_methods: []
        allow_headers: []
        expose_headers: []
        max_age: 0
        hosts: []
        allow_credentials: false
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['http://localhost:5173','https://front-partiel.malakayalauvergnat.com']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
            allow_credentials: true
            expose_headers: ['Authorization']
        '^/login':
            allow_origin: ['http://localhost:5173','https://front-partiel.malakayalauvergnat.com']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'OPTIONS']
            max_age: 3600
            allow_credentials: true
            expose_headers: ['Authorization']
        '^/register':
            allow_origin: ['http://localhost:5173','https://front-partiel.malakayalauvergnat.com']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'OPTIONS']
            max_age: 3600
            allow_credentials: true
            expose_headers: ['Authorization']

